timezone: America/Denver
encoding: utf-8
markdown: kramdown
exclude:
  - README.md
  - LICENSE
  - docker-compose.yml
  - .gitignore
  - .sass-cache/
  - .jekyll-cache/
  - template-bare.html
  - template-layout.html
  - template.md
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
sass:
  sass_dir: _sass  
